version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:15.4'
    container_name: january-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: january
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    container_name: january-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./volumes/redis/:/data

  #  start MariaDB, and ensure that data is stored to a mounted volume
  mariadb:
    image: 'mariadb:10.6'
    container_name: january-mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: january
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password

    volumes:
      - ./volumes/mariadb:/docker-entrypoint-initdb.d
